//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoboWorker3.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.betfair.com/global/v3/BFGlobalService")]
        public string ParseLiteWithAPIMultiThreadMultiMarket_com_betfair_api_BFGlobalService {
            get {
                return ((string)(this["ParseLiteWithAPIMultiThreadMultiMarket_com_betfair_api_BFGlobalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.betfair.com/exchange/v3/BFExchangeService")]
        public string ParseLiteWithAPIMultiThreadMultiMarket_com_betfair_api1_BFExchangeService {
            get {
                return ((string)(this["ParseLiteWithAPIMultiThreadMultiMarket_com_betfair_api1_BFExchangeService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.betfair.com/exchange/v3/BFExchangeService")]
        public string ParseLiteWithAPIMultiThreadMultiMarket_bf_exhange_BFExchangeService {
            get {
                return ((string)(this["ParseLiteWithAPIMultiThreadMultiMarket_bf_exhange_BFExchangeService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.betfair.com/global/v3/BFGlobalService")]
        public string ParseLiteWithAPIMultiThreadMultiMarket_bf_global_BFGlobalService {
            get {
                return ((string)(this["ParseLiteWithAPIMultiThreadMultiMarket_bf_global_BFGlobalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.betfair.com/exchange/v3/BFExchangeService")]
        public string RoboWorker3_bf_exhange_BFExchangeService {
            get {
                return ((string)(this["RoboWorker3_bf_exhange_BFExchangeService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.betfair.com/global/v3/BFGlobalService")]
        public string RoboWorker3_bf_global_BFGlobalService {
            get {
                return ((string)(this["RoboWorker3_bf_global_BFGlobalService"]));
            }
        }
    }
}
